find_package(OpenMP QUIET REQUIRED)
if(OPENMP_FOUND)
  list(APPEND CMAKE_C_FLAGS ${OpenMP_C_FLAGS})
  list(APPEND CMAKE_CXX_FLAGS ${OpenMP_CXX_FLAGS})
else()
  message(WARNING "std_ai_api: Cannot find OpenMP, turn off the `USE_OPENMP` option automatically.")
  set(USE_OPENMP OFF)
  return()
endif()